#!/usr/bin/env bash
set -euo pipefail

SYNC_DIR=".codex-upstream-sync"
STATE_FILE="$SYNC_DIR/state.env"

die() {
  echo "::error::$*" >&2
  exit 1
}

write_output() {
  local key="$1"
  local value="$2"
  if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
    printf '%s=%s\n' "$key" "$value" >>"$GITHUB_OUTPUT"
  fi
}

run_optional_tests() {
  local command="$1"
  if [[ -z "$command" ]]; then
    return
  fi

  echo "Running test command: $command"
  bash -lc "$command"
}

git_push() {
  local refspec="$1"
  local token="$2"
  local origin_url
  origin_url="$(git remote get-url origin)"

  case "$origin_url" in
    https://github.com/*|http://github.com/*)
      git -c "http.https://github.com/.extraheader=AUTHORIZATION: bearer $token" push origin "$refspec"
      ;;
    *)
      git push origin "$refspec"
      ;;
  esac
}

create_pull_request() {
  local target_branch="$1"
  local sync_branch="$2"
  local commit_sha="$3"
  local upstream_repository="$4"
  local upstream_ref="$5"

  command -v gh >/dev/null 2>&1 || die "mode=pr requires the GitHub CLI (gh)"

  mkdir -p "$SYNC_DIR"
  local body_file="$SYNC_DIR/pr-body.md"
  {
    echo "Automated upstream sync generated by Codex upstream sync."
    echo
    echo "- Upstream: \`$upstream_repository\`"
    echo "- Upstream ref: \`$upstream_ref\`"
    echo "- Merge commit: \`$commit_sha\`"
    echo
    echo "Review the merge result before merging."
  } >"$body_file"

  GH_TOKEN="${INPUT_GITHUB_TOKEN:-}" gh pr create \
    --base "$target_branch" \
    --head "$sync_branch" \
    --title "Sync upstream $upstream_ref into $target_branch" \
    --body-file "$body_file"
}

main() {
  [[ -f "$STATE_FILE" ]] || die "Missing sync state file: $STATE_FILE"
  # shellcheck source=/dev/null
  source "$STATE_FILE"

  local github_token="${INPUT_GITHUB_TOKEN:-}"
  local test_command="${INPUT_TEST_COMMAND:-}"
  local commit_message="${INPUT_COMMIT_MESSAGE:-chore: sync upstream}"
  local upstream_repository="${INPUT_UPSTREAM_REPOSITORY:-}"
  local upstream_ref_input="${INPUT_UPSTREAM_REF:-${UPSTREAM_REF:-main}}"

  [[ -n "${MODE:-}" ]] || die "Missing MODE in state file"
  [[ -n "${TARGET_BRANCH:-}" ]] || die "Missing TARGET_BRANCH in state file"
  [[ -n "${SYNC_BRANCH:-}" ]] || die "Missing SYNC_BRANCH in state file"
  [[ -n "${UPSTREAM_COMMIT:-}" ]] || die "Missing UPSTREAM_COMMIT in state file"
  [[ "$MODE" == "pr" || "$MODE" == "push" ]] || die "Invalid mode '$MODE'. Expected 'pr' or 'push'."

  if [[ -n "$(git diff --name-only --diff-filter=U)" ]]; then
    git diff --name-only --diff-filter=U >&2
    die "Unresolved merge conflicts remain"
  fi

  git diff --check
  run_optional_tests "$test_command"

  rm -rf "$SYNC_DIR"
  git add -u
  if git diff --cached --quiet; then
    die "Merge produced no staged changes"
  fi

  git commit \
    -m "$commit_message" \
    -m "Upstream: $upstream_repository@$upstream_ref_input ($UPSTREAM_COMMIT)"

  local commit_sha
  commit_sha="$(git rev-parse HEAD)"

  write_output changed true
  write_output branch "$SYNC_BRANCH"
  write_output commit_sha "$commit_sha"

  case "$MODE" in
    push)
      [[ -n "$github_token" ]] || die "github-token is required for mode=push"
      git_push "HEAD:refs/heads/$TARGET_BRANCH" "$github_token"
      write_output merge_status pushed
      write_output pr_url ""
      ;;
    pr)
      [[ -n "$github_token" ]] || die "github-token is required for mode=pr"
      git_push "HEAD:refs/heads/$SYNC_BRANCH" "$github_token"
      local pr_url
      pr_url="$(create_pull_request "$TARGET_BRANCH" "$SYNC_BRANCH" "$commit_sha" "$upstream_repository" "$upstream_ref_input")"
      write_output merge_status pr
      write_output pr_url "$pr_url"
      ;;
  esac
}

main "$@"
